### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ulatalib** [Gibberlings3/EET#114] opened 2023-09-23 14:40 UTC
//ERROR: COPY ~EET/temp/EET.lnk~ ~C:\Users\Ula~ FAILED: cannot open target
//Stopping installation because of error.
//Stopping installation because of error.
//Stopping installation because of error.
//ERROR Installing [EET core (resource importation)], rolling back to previous state
//Will uninstall 14673 files for [EET\EET.tp2] component 0.
//Uninstalled    14673 files for [EET\EET.tp2] component 0.
//ERROR: Sys_error("C:\\Users\\Ula: Permission denied")
//PLEASE email the file Setup-EET.debug to K4thos (swit)
//Automatically Skipping [EET core (resource importation)] because of error.
//Using Language [English]
//[.\lang\en_us\dialog.tlk] created, 271985 string entries
//NOT INSTALLED DUE TO ERRORS EET core (resource importation)
//
//WARNING: EET:0 has encounter errors durring installation, exited with ExitCode = 2
//INSTALLATION FINISHED.
 
I'm installing EET Using project Infinity
My Game folders in D, I don't know why project infinity is giving me error about C folder

Edit: I downloaded EET using the green Button (code>download as zip) because for some reason the official Release contain only the EET Folder, without the exe and other folders, and I can't install EET without them

**Comment by ulatalib** [comment] 2023-09-23 14:48
My game folders in D, I don't know what the setup trying to do in C folder

**Comment by GraionDilach** [comment] 2023-09-23 17:20
Duplicate of #69 most likely. By default, EET tries to create a desktop shortcut and it fails at that step.

PI doesn't need the exes btw and can't suppőly the -s flag to bypass the desktop shortcut creation.

**Comment by ulatalib** [comment] 2023-09-23 20:54
hmm, my user name do have a space.
I bypassed the error by giving my user full control of the c folder and it suddenly worked!
But I don't have EET exe on my desktop, I start the game by using the original exe of the BG2.

**Closed** 2024-03-25 10:15 UTC
Labels: bug
